### ISSUE TITLE
Intercept Visit creation to determine payment workflow

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-server#21]
- [ ] If the Visit Type is Admission, check the [workflow configuration](https://github.com/HospitalRun/hospitalrun-frontend/issues/462) that defines whether a deposit is needed. If yes, notify the user that saved the record that the patient must be directed to the Cashier's desk. 
- [ ] If the Visit Type is Clinic, check the [workflow configuration](https://github.com/HospitalRun/hospitalrun-frontend/issues/462) that defines Clinic Visit prepayment is required. If yes, put the Visit in a Pending Payment payment_state and notify the user that saved the record that the patient must be directed to the Cashier's desk.
- [ ] If the Visit Type is Followup, check the [workflow configuration](https://github.com/HospitalRun/hospitalrun-frontend/issues/462) that defines Followup Visit prepayment is required. If yes, put the Visit in a Pending Payment payment_state and notify the user that saved the record that the patient must be directed to the Cashier's desk.
- [ ] If the Visit Type is Lab, check the [workflow configuration](https://github.com/HospitalRun/hospitalrun-frontend/issues/462) that defines if Outpatient Lab prepayment is required. If yes, put the Visit in a Pending Payment payment_state and notify the user that saved the record that the patient must be directed to the Cashier's desk.
- [ ] If the Visit Type is Clinic or Followup and a Lab Request is created by the Examiner, check the [workflow configuration](https://github.com/HospitalRun/hospitalrun-frontend/issues/462) that defines if Outpatient Lab prepayment is required. If yes, put the Visit in a Pending Payment payment_state and notify the user that saved the record that the patient must be directed to the Cashier's desk.
- [ ] If the Visit Type is Imaging, check the [workflow configuration](https://github.com/HospitalRun/hospitalrun-frontend/issues/462) that defines Outpatient Imaging prepayment is required. If yes, put the Visit in a Pending Payment payment_state and notify the user that saved the record that the patient must be directed to the Cashier's desk.
- [ ] If the Visit Type is Clinic or Followup and a Imaging Request is created by the Examiner, check the [workflow configuration](https://github.com/HospitalRun/hospitalrun-frontend/issues/462) that defines if Outpatient Imaging prepayment is required. If yes, put the Visit in a Pending Payment payment_state and notify the user that saved the record that the patient must be directed to the Cashier's desk.
- [ ] If the Visit Type is Medication, check the [workflow configuration](https://github.com/HospitalRun/hospitalrun-frontend/issues/462) that defines Outpatient Medication prepayment is required. If yes, put the Visit in a Pending Payment payment_state and notify the user that saved the record that the patient must be directed to the Cashier's desk.
- [ ] If the Visit Type is Clinic or Followup and a Lab Request is created by the Examiner, check the [workflow configuration](https://github.com/HospitalRun/hospitalrun-frontend/issues/462) that defines if Outpatient Medication prepayment is required. If yes, put the Visit in a Pending Payment payment_state and notify the user that saved the record that the patient must be directed to the Cashier's desk.

Note 
- frontend related [Workflow tickets are here](https://github.com/HospitalRun/hospitalrun-frontend/labels/Workflow).

![hospitalrun patient flow](https://cloud.githubusercontent.com/assets/929261/15227446/48bb07f4-1855-11e6-9ab8-d85fd78b21cb.jpeg)

**Comment by tangollama** [comment]
Additional thoughts: from a technical perspective the workflow database listeners need to be examining change to the following items on both creation and update (state change):

- Visits
- Medication requests
- Lab requests
- Imaging requests

**Comment by tangollama** [comment]
Here's the design doc that we put together for this issue. https://docs.google.com/document/d/1WnFpwDQ6VabKpKMBCsz8NhAL17VgRdvS7vap7el3YW4/edit
